 
-- MySQL Script generated by MySQL Workbench
-- mar 21 may 2024 17:29:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Exam
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Exam` ;

-- -----------------------------------------------------
-- Schema Exam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Exam` DEFAULT CHARACTER SET utf8 ;
USE `Exam` ;

-- -----------------------------------------------------
-- Table `Exam`.`Berria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exam`.`Berria` ;

CREATE TABLE IF NOT EXISTS `Exam`.`Berria` (
  `idBerria` INT NOT NULL AUTO_INCREMENT,
  `izenburua` VARCHAR(45) NULL,
  `testua` VARCHAR(256) NULL,
  `argitalpen-data` DATETIME NULL,
  PRIMARY KEY (`idBerria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exam`.`Kategoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exam`.`Kategoria` ;

CREATE TABLE IF NOT EXISTS `Exam`.`Kategoria` (
  `idKategoria` INT NOT NULL AUTO_INCREMENT,
  `izena` VARCHAR(45) NULL,
  PRIMARY KEY (`idKategoria`),
  UNIQUE INDEX `izena_UNIQUE` (`izena` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exam`.`Esleipena`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exam`.`Esleipena` ;

CREATE TABLE IF NOT EXISTS `Exam`.`Esleipena` (
  `idEsleipena` INT NOT NULL AUTO_INCREMENT,
  `Berria_idBerria` INT NOT NULL,
  `Kategoria_idKategoria` INT NOT NULL,
  PRIMARY KEY (`idEsleipena`),
  INDEX `fk_Esleipena_Berria_idx` (`Berria_idBerria` ASC) VISIBLE,
  INDEX `fk_Esleipena_Kategoria1_idx` (`Kategoria_idKategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Esleipena_Berria`
    FOREIGN KEY (`Berria_idBerria`)
    REFERENCES `Exam`.`Berria` (`idBerria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Esleipena_Kategoria1`
    FOREIGN KEY (`Kategoria_idKategoria`)
    REFERENCES `Exam`.`Kategoria` (`idKategoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Exam`.`Kategoria`
-- -----------------------------------------------------
START TRANSACTION;
USE `Exam`;
INSERT INTO `Exam`.`Kategoria` (`idKategoria`, `izena`) VALUES (1, 'Kirolak');
INSERT INTO `Exam`.`Kategoria` (`idKategoria`, `izena`) VALUES (2, 'Teknologiak');
INSERT INTO `Exam`.`Kategoria` (`idKategoria`, `izena`) VALUES (3, 'Ekonomia');

COMMIT;

